# Generated by Django 4.2.6 on 2023-10-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirQualityData',
        ),
    ]
