# -*- coding: utf-8 -*-
"""AIR QUALITY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1egJkAF620ajBg1c_fwdyb-A_CT31Qz45
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv('D:\Internship Luminar\Air Quality\city_day.csv')
df

df.dtypes

df.columns

df.shape

df.info()

df.nunique()

df.describe()

df.dropna(inplace=True) 
df=df.reset_index(drop=True)
df

# Select only numeric columns for correlation calculation
numeric_columns = df.select_dtypes(include=[np.number])

# Calculate the correlation matrix
correlation_matrix = numeric_columns.corr()

# Create a heatmap to visualize the correlations
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, cmap="coolwarm", annot=True)

df_city_day = df.copy()
df_city_day.columns

pollutants = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3','CO', 'SO2', 'O3', 'Benzene', 'Toluene', 'Xylene']
df_city_day = df_city_day[pollutants]
print('Distribution of different pollutants in last 5 years')
df_city_day.plot(kind='line',figsize=(18,18),cmap='coolwarm',subplots=True,fontsize=9)

x=df.drop(['City','Date','AQI_Bucket'],axis=1).values
y=df['AQI_Bucket'].values
x

y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=42)
x_train

x_test

y_train

y_test

from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

df1=pd.DataFrame({'y_test':y_test,'y_pred':y_pred})
df1

from sklearn.metrics import accuracy_score,r2_score,confusion_matrix,classification_report
print('confusion_matrix','\n',confusion_matrix(y_test,y_pred))
print('*'*100)
print('accuracy_score is:',accuracy_score(y_test,y_pred))
print('*'*100)
print('classification report:',classification_report(y_test,y_pred))